apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: truenas-transport
  namespace: traefik
spec:
  insecureSkipVerify: true
---
apiVersion: v1
kind: Service
metadata:
  name: truenas-svc
  namespace: traefik
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-svc
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.100.11
    ports:
      - port: 443
        name: https
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-lan-route
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`truenas.local.nasbenito.com`)
    kind: Rule
    services:
    - name: truenas-svc
      port: 443
      serversTransport: truenas-transport
  tls:
    secretName: wildcard-local-nasbenito-com-tls