apiVersion: v1
kind: Namespace
metadata:
    name: cert-manager
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWkRZQ1VtcTZHMTcrbmR3
            TTRKaG9YY0FCTGlidlVmMFdPUmJUeVMwL0ZRClA1QnVsRGlXNWNrSlRsQXpkNkN3
            VXNMNUpIVVhNMHkydGdPeXlrVHJEVEUKLS0tIHRJRzRHWVlrd3RyRk1GS20ySURj
            YVBrMGsrYU1DRUJBeDJIVDE2aXJjbW8KOFqFeiMCkFj9cjgnrcyW0GF7PyyM5tnJ
            MgfLIxVmdEN7oaoe9gA/BRoxPtVGNUh24lrF2IKMaoAthIRA1JnVgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T11:33:30Z"
    mac: ENC[AES256_GCM,data:OMEp7luneqY4kIcquJdkxXtVCYzuKtY9hBnJ8eP5zg8tNQ8isMVWvNh8vhhdmO2NxNw83lqGT8GwAA6dA2bcnwoUIeDhb8ZIn83Aa2qCugwAbIYnPON/5qMSNIBZHKaOREvmSIdo8hBo8u8zuTlvNgmu7DZBNRS2p40QVdWOOO8=,iv:qsGm2l/nAtiaXrSaZk21ovSDLQL1ytuDWlSqgb0v1n4=,tag:pZkbvE/H4B/IHZOj74ACmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:4QLOoZOKfT3o1bsekGKZjrma6rQAcE0vM0P2gpppaodqMvlqkPLmqQ==,iv:w2WxP/g6dS0Mtc5MSulYKxl3J5oC9E4+hL3hYFa80tY=,tag:N8F6K+tlhrARk3T0a+Yg7A==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWkRZQ1VtcTZHMTcrbmR3
            TTRKaG9YY0FCTGlidlVmMFdPUmJUeVMwL0ZRClA1QnVsRGlXNWNrSlRsQXpkNkN3
            VXNMNUpIVVhNMHkydGdPeXlrVHJEVEUKLS0tIHRJRzRHWVlrd3RyRk1GS20ySURj
            YVBrMGsrYU1DRUJBeDJIVDE2aXJjbW8KOFqFeiMCkFj9cjgnrcyW0GF7PyyM5tnJ
            MgfLIxVmdEN7oaoe9gA/BRoxPtVGNUh24lrF2IKMaoAthIRA1JnVgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T11:33:30Z"
    mac: ENC[AES256_GCM,data:OMEp7luneqY4kIcquJdkxXtVCYzuKtY9hBnJ8eP5zg8tNQ8isMVWvNh8vhhdmO2NxNw83lqGT8GwAA6dA2bcnwoUIeDhb8ZIn83Aa2qCugwAbIYnPON/5qMSNIBZHKaOREvmSIdo8hBo8u8zuTlvNgmu7DZBNRS2p40QVdWOOO8=,iv:qsGm2l/nAtiaXrSaZk21ovSDLQL1ytuDWlSqgb0v1n4=,tag:pZkbvE/H4B/IHZOj74ACmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0