apiVersion: v1
kind: Namespace
metadata:
    name: cert-manager
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWkRZQ1VtcTZHMTcrbmR3
            TTRKaG9YY0FCTGlidlVmMFdPUmJUeVMwL0ZRClA1QnVsRGlXNWNrSlRsQXpkNkN3
            VXNMNUpIVVhNMHkydGdPeXlrVHJEVEUKLS0tIHRJRzRHWVlrd3RyRk1GS20ySURj
            YVBrMGsrYU1DRUJBeDJIVDE2aXJjbW8KOFqFeiMCkFj9cjgnrcyW0GF7PyyM5tnJ
            MgfLIxVmdEN7oaoe9gA/BRoxPtVGNUh24lrF2IKMaoAthIRA1JnVgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T17:20:02Z"
    mac: ENC[AES256_GCM,data:xhoc3zQJhx+cN5uDY60/rCC3fRoB8qFXU9c5IeQTOEKodCmoBsHvZ2QdL5YmOmz7T9pdRnl05+rfjYgHuj4gPWu6ukdPrvoOj4uZ9PoKE+7xalad4eBPPTo7anShepC0yaTxGUF9PYOkOkueLZhYsrD4MbQ0cK+IeaWLcE+n7dY=,iv:QIAbiBJD8yRXCEnKsDxdRg/Jq0Dr4WGsHpwIIHG+9Mc=,tag:NAElRcgc11qnYRo/pqz3rA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:+FyfabVCattHDwpUIFJCZA0sAKnvzoymXSekJuRP6+mZdAQ/leATGg==,iv:UMemIGwsDkg1cDHnECr44uMo4FgL2AeW81f836nSD0g=,tag:9rH+p/ij0+Eezzfg8gBxlg==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWkRZQ1VtcTZHMTcrbmR3
            TTRKaG9YY0FCTGlidlVmMFdPUmJUeVMwL0ZRClA1QnVsRGlXNWNrSlRsQXpkNkN3
            VXNMNUpIVVhNMHkydGdPeXlrVHJEVEUKLS0tIHRJRzRHWVlrd3RyRk1GS20ySURj
            YVBrMGsrYU1DRUJBeDJIVDE2aXJjbW8KOFqFeiMCkFj9cjgnrcyW0GF7PyyM5tnJ
            MgfLIxVmdEN7oaoe9gA/BRoxPtVGNUh24lrF2IKMaoAthIRA1JnVgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T17:20:02Z"
    mac: ENC[AES256_GCM,data:xhoc3zQJhx+cN5uDY60/rCC3fRoB8qFXU9c5IeQTOEKodCmoBsHvZ2QdL5YmOmz7T9pdRnl05+rfjYgHuj4gPWu6ukdPrvoOj4uZ9PoKE+7xalad4eBPPTo7anShepC0yaTxGUF9PYOkOkueLZhYsrD4MbQ0cK+IeaWLcE+n7dY=,iv:QIAbiBJD8yRXCEnKsDxdRg/Jq0Dr4WGsHpwIIHG+9Mc=,tag:NAElRcgc11qnYRo/pqz3rA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0

