apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 30m
  chart:
    spec:
      chart: minio
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: minio
  values:
    mode: standalone

    existingSecret: minio-root

    persistence:
      enabled: true
      storageClass: longhorn
      size: 50Gi

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "2"
        memory: 2Gi

    service:
      type: ClusterIP
      port: 9000

    consoleService:
      type: ClusterIP
      port: 9001
