apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: minio
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: minio
  values:
    mode: standalone

    existingSecret: minio-root

    persistence:
      enabled: true
      storageClass: longhorn
      size: 300Gi

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "2"
        memory: 2Gi

    service:
      type: ClusterIP
      ports:
        api: 9000

    console:
      enabled: true
      service:
        type: ClusterIP
        ports:
          http: 9001

    environment:
      MINIO_BROWSER_REDIRECT_URL: "https://minio.local.nasbenito.com"
      MINIO_IDENTITY_OPENID_CLAIM_USERINFO: "on"

    oidc:
      enabled: true
      configUrl: "https://auth.nasbenito.com/application/o/minio/.well-known/openid-configuration"
      existingClientSecretName: "minio-oidc"
      existingClientIdKey: "client_id"
      existingClientSecretKey: "client_secret"
      claimName: "policy"
      scopes: "openid,profile,email"
      redirectUri: "https://minio.local.nasbenito.com/oauth_callback"
      displayName: "Log in with Authentik"