apiVersion: v1
kind: Secret
metadata:
    name: minio-oidc
    namespace: minio
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:mdlsfq4rrdzc1WyKvlxDXVB/1T992r3pz+8TLxmD4Q0YjbuCZB6MFA==,iv:ABl7wiYCOuX5oaoKGgMwO7jF9VB/M1RaICOTBLcpiaM=,tag:OYDBQ8jXsh9ZtOWZQTGhIA==,type:str]
    client_secret: ENC[AES256_GCM,data:KOFToHeHVK1ZaUTvHAgjXLfZOEbLbNU1G155YFtiR8KbGHBeMphWAG9GNZTZ1pCz7sHrvl38GThbikGanfoVLG/djpLcAerTeKs+J22agND6FziXhvibAYNOMeH9gji/OxmDxWLJWmJ7604n3a/JUTTIShqg3gwUwJduEX/BYQw=,iv:H2JIT/ZCvAPFwx8W3keVjgxhwATaLSTBBUFua51FrVE=,tag:8YaAbmyMLmMvZDS++HTCPA==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZkN1T0d1T1gyaHA5dGVI
            bzRpYjlCVW10ZUhlK25pRk92UU92OFNyRG4wClZTdUtCTmZBOUlZQnVrbEFKY095
            dDdOS0hrZHJ6ekhWUUtTSWxXTjJuTFEKLS0tIFM2M0RiY2I3MHpNT1hHN0hvVTRy
            eFRNTDd6U3pUSllid1o4V1dOam1YSVkK80QVSHxI/o5joJOYTFGknf9jrToGlJql
            a7pklZ14LL7FfQ+XSf201GnSnjhqVfSoK/gFeJ4M+ouCLehmDH0N5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T00:10:15Z"
    mac: ENC[AES256_GCM,data:5KvqCU4pm+ko1OiXcurAU2Fd/Lmy1cuYske1VZL5Sb+laSEhsDRXxeHJRxRXdz35Pinl1HpHhx5iNY912ay2wEgC3jpfMIBaXJNQ9viJJCUOS6AIORhWl+Fl9LLH94dVyVfBwtKQAAhzxgEMoiIuygn9kJy8KR4Cqpqrk7f4QwQ=,iv:ryutDtWfAde2vQ846j5blzGULx/uISkrVDgx2gL+PX4=,tag:QzBLmvE+aP3wD2JGl4xasw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
