apiVersion: v1
kind: Secret
metadata:
    name: minio-root
    namespace: minio
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:xSa50GZ/v2c/ZA==,iv:H+1/9/ghJXktsG4B+NeA1PAiFrxlS+XmxIqLnPX/UHE=,tag:E7BjNc4mYFLwTUJWEoaQSQ==,type:str]
    rootPassword: ENC[AES256_GCM,data:YhFTQKYkr0i1dtniuLglOKCL3Fxv5m8FnqmJ4PSnsmXZNzTlCg0nXE0ZCfvKRXv/,iv:gAwMJD6QyHuBJvjfy4ForzXM5DFbE3AtbYKMH9ZXq3M=,tag:HkICwS9K7pjUiQ4RY2b6iw==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMTlwUWZhbjFxbzRjL2tZ
            RHRwVnZpeWQreExRa1JKYXU2d0p6NnBLSUFrCmwvekg4ZWhmbWk4dlRyT1Myd2Mx
            Q3NWeDJOclE1RHAxdmJEWVhXaUFTcEkKLS0tIEh4WmxwNDVKcGJrMWp6WkJoTGd5
            Q3I5Z04zamI3bWdiRW5HVUhHNS9ITk0KbY44NwHEkgyALIcSro+Ym5kARY0EtRjz
            bvP1XSol5cV5OU275rSgjPBEX/HpL+R+PIQlxWut10NPQGnhgT76xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T21:01:27Z"
    mac: ENC[AES256_GCM,data:eO3wi+thcQCgR8zKf4dnIcuJGDnL2kiccjk1O2dhMYPUpwUTvM0UeMLaTtZhBwdmEmO1eELmokwk5KQe8d0nT4L9laEMBBENNvCXfVbR1YCSk1xnR7VSn/IAOTCCVp9GjeV8wcvuGMhJdeZwkcAlcPukPyYT7zWQrCa1U9k6PYI=,iv:gDUKZ+QhR7MQL38vZPexJd9SNBqfmOLCqfrINErAWfs=,tag:vEYWC0mkLEL8LHjfBY8+YA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
