apiVersion: v1
kind: Secret
metadata:
    name: minio-oidc
    namespace: minio
type: Opaque
stringData:
    MINIO_IDENTITY_OPENID_CLIENT_ID: ENC[AES256_GCM,data:1BTeCiTaR8QUelIyoxb9w1t6JNEBi6RoPrHDlAkl8YFna2F22Yza6Q==,iv:jOqrs33DPp92CW/tuY5lGjnYvbrplnvBPN3Jfv374uY=,tag:ukY9b//z01Pa7P3UZOs38A==,type:str]
    MINIO_IDENTITY_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:PnfRAYaVKCuNmeea6V6OIMJ9cNMaTdDhvd62AKlDGxdPOTvZioKTN8lhIfvnP+SPEcmoO5I9PFHVY2wvFeve61PgrimZbCI8/c6f0R9XKFuKjb+ozVogIUISwkfcrW5GqdkthS934PBTvF+vKcQyoBR1QCcVa3mO4TD7EPrQhYg=,iv:b2ey6XY1fODQGOz2aM9fxtBgZgsXAxR8omau5ZRkJqQ=,tag:wVV6lWvUUU7oqW61TR1aeA==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZkN1T0d1T1gyaHA5dGVI
            bzRpYjlCVW10ZUhlK25pRk92UU92OFNyRG4wClZTdUtCTmZBOUlZQnVrbEFKY095
            dDdOS0hrZHJ6ekhWUUtTSWxXTjJuTFEKLS0tIFM2M0RiY2I3MHpNT1hHN0hvVTRy
            eFRNTDd6U3pUSllid1o4V1dOam1YSVkK80QVSHxI/o5joJOYTFGknf9jrToGlJql
            a7pklZ14LL7FfQ+XSf201GnSnjhqVfSoK/gFeJ4M+ouCLehmDH0N5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T20:08:24Z"
    mac: ENC[AES256_GCM,data:1ZQ2cnFGaWxPGnBsEKypox4IpQUAmC3imAKPYLWa1YIy72rYOTa63vxOuvInnx3fEx7neilBy5BGLzYigtTM5Mq1lyEyi5rWhaRTWgM/qNBlUwD+M/yRplnNLcOcmQzD6qQ1d1o1ZP32DQeNrzRzT+vtJqwYu2bu1205R56/z/0=,iv:AfCEjtvGAyLrInTnoOL4gnqOq0zYLTHDnfsZCxcs5Oc=,tag:yWHBjhjLqCmlhxW3QD0V8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
