apiVersion: v1
kind: Secret
metadata:
    name: minio-oidc
    namespace: minio
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:rL3C+QqkVTH4QQIIZ0619xzdOrjZ7N3m7ByPzERKwnOxgkoLhCjaOw==,iv:soy3j7SnyPzDEYg/sG+Qdqu1kNZ4Hm45iWt7LFMaLSc=,tag:gAUYSMT3WRnL2IsaIfA6Ow==,type:str]
    client-secret: ENC[AES256_GCM,data:GVLUJcIQKSjUPEYp5iHCuUkmfe2Mog/L3hZtmFHTktQsMS5CrfxnpZEu863CaPKNyu9pJGxBjQ1KhfK3Ad3uTR7h+OnyDgls183+CfMcoh2iD9YTOSynHFQJn7x8lg7/7W3ZpzyvBFu7Bu6jZqaDgwk0oSYA4012Y4sJh+7J0GY=,iv:DyawhZBzJ+IIuCQaBU3GOapWAwaLuIZrK8eXE/iDGvs=,tag:VB4xXetNQebEH16fkDgtJA==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZkN1T0d1T1gyaHA5dGVI
            bzRpYjlCVW10ZUhlK25pRk92UU92OFNyRG4wClZTdUtCTmZBOUlZQnVrbEFKY095
            dDdOS0hrZHJ6ekhWUUtTSWxXTjJuTFEKLS0tIFM2M0RiY2I3MHpNT1hHN0hvVTRy
            eFRNTDd6U3pUSllid1o4V1dOam1YSVkK80QVSHxI/o5joJOYTFGknf9jrToGlJql
            a7pklZ14LL7FfQ+XSf201GnSnjhqVfSoK/gFeJ4M+ouCLehmDH0N5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T19:04:36Z"
    mac: ENC[AES256_GCM,data:Wlbfmz8Oo7IUesnu66/10fhy87bhF/hRMwTrpZn3Pp680IzBAmPlhZPKMba4wiL4mZ6VH1Y4m7CTQy/lHD/8vpsc6x0AhGldN7TRXt0Gxr3mPniSV1Io3G+rAaq1RNnzutl4lJxG3fp4qbtCnhKL3FEJ6excvt0SYBInXSiHTwQ=,iv:DKZnqJAbYn8AwpkNJmPD5slU/EMu/xcZYZxgbQUpabU=,tag:blcqumtpnvilP1NrFMBtZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
