apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 10m
  chart:
    spec:
      chart: metallb
      version: "0.14.5"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    controller:
      replicas: 1
    speaker:
      tolerations:
        - operator: Exists
spec:
  timeout: 10m
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true