apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test
  namespace: nfs-csi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-test
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
  namespace: nfs-csi
spec:
  containers:
    - name: test
      image: debian:bookworm-slim
      command: ["bash","-lc","while true; do echo \"ok $(date -u)\" >> /data/test.txt; sleep 60; done"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: nfs-test