apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test
  namespace: nfs-csi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-test
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
  namespace: nfs-csi
spec:
  containers:
    - name: test
      image: busybox:1.36
      command: ["sh", "-c", "echo ok $(date) >> /data/test.txt && sleep 60"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: nfs-test