apiVersion: v1
kind: Secret
metadata:
    name: authentik-values
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:sO/IzE2DRgxZ/tPi4+K0EDGk0l2GgLXK9//Eo5T7e9ceRS19511fWe0/DneplpNoOzpVbWNqanLVfhC66XS9zkf93GJv3hXK/g1utbIKTMhDURFGvHHzKwIjLVhqjvJqgnGuVwr6T+obuOk2mGsvecKqkkkqlljZZPwX4aVM6gm3JLa5x0oRl2eoIgcbBE3Krl6PpDUJbr5byyjVUzqDY6iBiaZMc/KwCdxt6qZEo0OQ14cYrvXHie2X2fK/ecDywOFxpNfkvc87EckZLIh5EgHpY9Xmu8m8FGCuvV2Wnpu3Q82i4Ve0kTfYjn6+kLjEXcz+4PLmdgw62dDg7l7XsXkz4x4hOxF5skyCpbIqnj7bWS4ZRYOvJILh0VGP9cfqyAyYx4XHEQaWSMg6YcJr1MRqgKBhLDzm0x1sdclW2dVxB9kMqJQt/8Zb104iypozJxSPD+xGzumFzVemwEB1pKiQfDZ2nBFifa7+6z48xf7ydWiV2OxB/OIhb4yJn17ilMxzNlVTHJ/PmsZF17laNslAq3/9I+E456jasgvk0h1hT1Wv6xRFwTK1XcB11cJQwFAdNUWFISHMO2DznaCaL5hQw2TyhBWqosQV1cHCFepCJLQ2cTsowZ5sJCfdaOUEuSEINuVwAS6LGk9Yiz1LW84cniXsJUsNovLLmLLRmjpGJVNMhbX568CzS9Mnbi0YkQ92J80yRUSROZCOJthsaXpk5fD6jLqs8Hgpc0AD+X5TaHQsTgk0qWqa+6v6rfSQwA1wuaomZUTBBD1vRQ5L8j79mitsq8ydmFKpfymj+1nwU3Rq8qzQgCx0Rt7lrGFH4miB8T3WR5bLS3i80XMYImNtzWUaUAE0mVl0D1+CN0r8uDcFbcEps7uNS8NtBD0C4dQnBjop7VjD4qwFRYp9GvmUEpT56WAqovad8yPJoWIoFvyk9zmowXN4lQDwVV0GImqJ1lUtWPzmBkeWgS4oGQ7L+XfmwqVeiBd4cVU/2CdBj4Nq3gAINs81mKq8Qrl6AuGZvrePKmxEfnETAU+Y6K1I5M1+dkvYimIgIR9dk+LuLPFGURB79LniFzKT1NWOmT437ivrIiC5HXUmkZ2F2lDaa6Iy+apGtLZW5CAU06y5b/U0swvPn3MQA8wCVFP2M8W1h2hSjaYVWN7H6UIXaQ/VdECAMc7bUcFD5JG2OlOY6y5NwgClBcJ8N39c8obJglgtQ0l/OCDavz4FM+t8vX09pOZnZIlu9vc=,iv:jgoTix3NWD7Hy9ne7H56EcIlI37aA4klpbYpe2c2l64=,tag:IiQsW+Si8toTFPpdfOEC+A==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYzBvV0N2YklJbjB5WUtM
            OXdLQllRUUV1L1R2TWdGbGZMbDVpWlpnelFVCjUyMzhMbGFVSnZtS0EvaWdtU05Z
            bHBGMUJzRFE3aGNjL2dSWmhnY0xHSTgKLS0tIDRUQVZ6ZjBrNEtFNE84bFdZMjBw
            SFJ5dDNtSlA3bEhaTVUyVTJOSDhnTFEKhoc+Zn1QvQYVRKjoTZ+HG58x+U93Evq1
            6fNLEOfAxgaUbNLspDHtlaOk/ec1cIjidefrA+kuv0PwQ1+NoMTKaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T21:25:54Z"
    mac: ENC[AES256_GCM,data:Et82RBaZaDUrgMus5Lvc6fvOaj6G5lhdgM9wODBUvLm+rQssE4iqh6W8tOA654xGbkltaHP8HDkdqWq17e+RLNCpRFQe9mFldOEiUnXUQTUuepXmKMKRL/VuNvAbgt9R4rui7AZa1yAnXUJx9z0GLdg2762O+yL6JLKsKGLHsg8=,iv:ii3WlwAFDoHLPgja9xBQFkyylmNg+2ETdau9Htqc74o=,tag:BlMSVKS66s+XumsMDDQ6uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
