apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-credentials
    namespace: authentik
type: Opaque
stringData:
    host: ENC[AES256_GCM,data:Pp4F0PKuF6AZ/5PgD3H1wFb3TdPEJqs=,iv:i3eNYN+NMzIGSdDIwm3U8WPFYMiY7dzha3kTcKf+IuE=,tag:PQGxaLk+2Ev7EFhIupt8mw==,type:str]
    port: ENC[AES256_GCM,data:Mpl9tQ==,iv:4BOKFTDAw+/6EPtrJmjbsKfYgerqPgRWSGmIRpq+/3Y=,tag:nQLdnzOnViGTMzDKt7oT1g==,type:str]
    username: ENC[AES256_GCM,data:JvaetQTUDCh8EO3drw==,iv:aAVGxRzwAP6vJw8FRgxzLe9bx7InSyBNbbexWBvMgGo=,tag:phZyFhsgL0LfN8xTOQP0fA==,type:str]
    password: ENC[AES256_GCM,data:PKQ/6Z7fI1pa6X/HAOapXZYOlwsnZvYs6B/csXV24VHmYuLtjpRTQ6/gL+4LqL5ofX8gKuCDZ/M5TYimuPBRzw==,iv:lme0U/r9keco4rdj6uGxAJFDLMoxwuI+4AtK+egJYB4=,tag:epBZBoM9LLYVbyn31EIhsg==,type:str]
    database: ENC[AES256_GCM,data:7tnrf+CFeCFv,iv:lCqslApa+24buRSDUNTcze3bEXqX6SLpXhN6Nw5jMzQ=,tag:PcgPX+VRJ3YC2iG4IlTM8Q==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSjUwbFhNb3hkRit2dm0r
            RlF4VUJOQ3FhUzJad1U5a2Z6bHlUalNucUJVClg1UjRrUWtHODVlY1ByeGFMTy9x
            aTJWaFNuN0hwTkl6UUJMdDZsc2VTNEEKLS0tIE5rREdHVmttNzhOTlhBeXlzNE0z
            Ri91OVhZNys5Nmk2ZXVLdDd6ZkdVZ00Kcey0OYrRkcsVSJuxNb5dUrCe67ur1uEp
            VxW7YIoTH3FTUR5RmJF/WmAyJJh0arXflbOnItBmoFxZdOx0IOXnUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T16:06:41Z"
    mac: ENC[AES256_GCM,data:g8lHQqG58VaeZXxLHzpfKIAAaGxzyvqihIxoHd9ED25Bv3lp07YRotcG1R2nTO5RW8Es/XYjZzdWRITS+pLsJneHbxlAbvXEveTXp1uauunB6Q+7VTT/k+svJTxAaJ+/XUQsj4Zl2uiqxoNzqaX7z9x2JlBw4+hU3Oyxi9VwIQA=,iv:SBwodBQkzWFMDHWNBxbcmFwanezwcY7MyRoF+EYRMEY=,tag:duZPMrYA3DvUqu+GQaWf0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
