apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: authentik
      interval: 1h

  valuesFrom:
    - kind: Secret
      name: authentik-values
      valuesKey: values.yaml

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
