apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-backups
  namespace: authentik
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-authentik
  resources:
    requests:
      storage: 20Gi