apiVersion: v1
kind: Secret
metadata:
    name: jetkvm-cloud-env
    namespace: jetkvm
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:zHZFuQ==,iv:DQWBPMixPSFowYbBqnxSp0SCi6Nvlkbei6g8p/L6azU=,tag:FhTfesyKIpAJlViKtetD1Q==,type:str]
    API_HOSTNAME: ENC[AES256_GCM,data:8WTPxju931k/P6a9VhF1hDp5Etgl9xY=,iv:Enj3Tu26V7Ej+uNXweW8bThyvKPKC+ecCZVvyzRk2Tk=,tag:iE3DHNpku8MPQDhU8BEc5Q==,type:str]
    APP_HOSTNAME: ENC[AES256_GCM,data:SymLB2hrQFBvKg217hz6veTT4ebBWXM=,iv:igETgyE2M4UECGpZqUiEaliuePIWYE8+eog4vTlrs9Y=,tag:QTAcR1QuNjGcUlyNyTdGZg==,type:str]
    COOKIE_SECRET: ENC[AES256_GCM,data:uWt/9MVb++5ltXe0LwZzfiYpDXca1HEjM6FiY93RiB+ukc4NNMuJyixVwbdLV4O/,iv:bRO0orGV5jltiky72xfxm1U1I4nFfqnWGM1FY7spg9Y=,tag:BQQYreDDBDRSMMjdjc3Cxg==,type:str]
    CORS_ORIGINS: ENC[AES256_GCM,data:iLZd1undhv6duKEzYoyfg0dMOzgpXqH1E2eS1xAcyQ==,iv:UCG2N8ufNzFDeO4mhCMa4lNfniSzkfZSiZVZIclEOVY=,tag:kfnEeztBj1ez09Mc7lWO8A==,type:str]
    ALLOWED_IDENTITIES: ""
    REAL_IP_HEADER: ENC[AES256_GCM,data:0qjqd6zTXNttmZeojtoS,iv:AIWBIr34VRw/Y3RNjgSyR94MuTS1p4ZMUNyKZSpLnR4=,tag:KfUJ++PEA5O6UlfLxz39IQ==,type:str]
    ICE_SERVERS: ""
    DATABASE_URL: ENC[AES256_GCM,data:8sUU4uYkHqiebYFRPUrE2zwB+Cff28T6ml2V0cumEXpYoQqJvL+u4l1vg1Bkh6NX2FCKmC7WldWqMrEWi/U68DnxNVu9sYfK+/GDQiUmCoy3PXXRCdxdH9D2kMGDEcSDMVjtfU/bzxNm6j2Ahag3BCoJuj3mjsodkW/Jj4Aj4nBroooO,iv:NNxDKhkZVdfyEksQi15C90hPczuZ3IQkSZWb8BYGrgE=,tag:Y/56Lbc/zPYvHHbTosAQYw==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVThzekdzbTkwTi8zSDNi
            eHgvL0VDZUpUanRCNkJiOVhUSlNqdjFDVkhRClZwTXAvcnVzNkJDYVJYczNva3g5
            OG80bWVUdVRWSTJpMlBBVk03NjZqZE0KLS0tIEhMNncwWnp0bDZmWlVXK29FOHEv
            NW5HNEI4bk9DS2ZyL3lKSEw4YS92R2sK/hZPRttLiLbAf03JXag2FAAy9GdPcShI
            IusK0OIG7LY8rhC+F67rjTPD494n+9ot8c3susNxcD09JayD5dE0nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T18:43:05Z"
    mac: ENC[AES256_GCM,data:iYbPtgzUX6uc9Gx4o3qFxVGtepm6n10qFZTVke0VKeGYMeeyXTb5Gou8sQXo8wAqzJGDWLbG7dtCVNBt6Ptz/BwC3qKYD/ZtXahXxHX56sLtCn4CBQP6LaEtwNKdHBI0wOIEK8DIUnhFfdur/x3bwe60MLsGhl+hHtqLbVEFg3M=,iv:anTsnanPlIuOltL0ptTF17IqNfgZHUNcTGkgxhp0eq8=,tag:FykPgzFZk3FxOzuBbwcP1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
