apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeipa-data
  namespace: freeipa
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi