apiVersion: v1
kind: ServiceAccount
metadata:
  name: freeipa-backup
  namespace: freeipa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: freeipa-backup
  namespace: freeipa
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: freeipa-backup
  namespace: freeipa
subjects:
  - kind: ServiceAccount
    name: freeipa-backup
    namespace: freeipa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: freeipa-backup