apiVersion: v1
kind: Secret
metadata:
    name: freeipa-bootstrap
    namespace: freeipa
type: Opaque
stringData:
    IPA_SERVER_HOSTNAME: ENC[AES256_GCM,data:LbQ0vvJePE+q7wj/zLI22jc/VBaZwJE=,iv:Usoqg1ruDEW5/WNGYxVFSNQz/4QqbxduNEeNrsDq5hw=,tag:djMtp8vEGNvIDmHfYtPmZw==,type:str]
    IPA_SERVER_DOMAIN: ENC[AES256_GCM,data:7to2ZfyyfcvsivfXAYqm0sUR0w==,iv:WSbWsTdf96KYntpdfXezr1uoer8IVPOoSUO9S7VSpy0=,tag:AR+ujZGaG3LrES8EvLpFmg==,type:str]
    IPA_SERVER_REALM: ENC[AES256_GCM,data:aLO8f9hK4w8JD/ombuv2qOQ5Hw==,iv:+WwtnzQgFdWcy3hqEwQKCfw7Pa82FL/frS1DH9+gdvw=,tag:3bL2nEbyumTil+pW7QnDYQ==,type:str]
    IPA_ADMIN_PASSWORD: ENC[AES256_GCM,data:mpCg9XCYHqCZkoontgGQ,iv:2VsCE8qX5rjAxVlcRUsrUWqfkn/3WhVLuL/vRsMMpLc=,tag:2OKk9IulKCHC6GftujsaSA==,type:str]
    IPA_DM_PASSWORD: ENC[AES256_GCM,data:7xt1Tb79TJuJORz7hRhW,iv:PAwVW2/vxXxFeZT1b3EkR+8YY4p/ZGWn7UNBCjjGfXw=,tag:5+MqrlrYPs4xHKuWVpunOQ==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTm8xdW0rRno5Q09OTFZC
            VHRuM3B2SjZwYXNMd3dLQTR1cVlmeHYvSFY4Ci9pUmZRY01CZDByTGl5N2VqT0NJ
            VEVud09idHhTcFZDNjZjR1dUVDFPcnMKLS0tIHZlQTdwcGpLSks0bkRQZE9kWjJG
            c3RGVnNZQ25UR0FQQmhvMWdXaTAvMDQK/9ab1bsuccN6zDnTzYzYawupo64ihGnq
            aRKN0qRNsqIYQrro4cK1xoV5JY16rZp1IEH2YSw/8IMpg6K18r5RGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T17:17:42Z"
    mac: ENC[AES256_GCM,data:fG63LfuAIx0r4CofjSd0Xh2RvbyU2jDfr/LjbJ/QA9QOmAzIuoCgyy10tuYmi04hkmDAqol0+s59P540e0CFUikJ0g8rOwX+G4ywP8LrS2KqF1GO1ba9SqVvcdY4MssOnF5FYObFzjzA7flLM4G+8O1YAy1ygVIRzCp/IK6w/PM=,iv:2nyzxwb8KpZfK9cm6Jq1b4nJ0azYlVqtJRjjdqMAHPw=,tag:e3nP1l1GcIhyACTEi2k+kQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
