apiVersion: v1
kind: Service
metadata:
  name: freeipa-lb
  namespace: freeipa
  annotations:
    metallb.universe.tf/address-pool: lan-pool
    metallb.universe.tf/loadBalancerIPs: "192.168.110.244"
spec:
  type: LoadBalancer
  selector:
    app: freeipa
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: ldap
      port: 389
      targetPort: 389
      protocol: TCP
    - name: ldaps
      port: 636
      targetPort: 636
      protocol: TCP
    - name: kerberos-tcp
      port: 88
      targetPort: 88
      protocol: TCP
    - name: kerberos-udp
      port: 88
      targetPort: 88
      protocol: UDP
    - name: kpasswd-tcp
      port: 464
      targetPort: 464
      protocol: TCP
    - name: kpasswd-udp
      port: 464
      targetPort: 464
      protocol: UDP