apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freeipa
  namespace: freeipa
spec:
  serviceName: freeipa
  replicas: 1
  selector:
    matchLabels:
      app: freeipa
  template:
    metadata:
      labels:
        app: freeipa
    spec:
      hostUsers: false
      terminationGracePeriodSeconds: 120
      containers:
        - name: freeipa
          image: freeipa/freeipa-server:almalinux-10
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: freeipa-bootstrap
          env:
            - name: DEBUG_NO_EXIT
              value: "1"
            - name: DEBUG_TRACE
              value: "1"
          args:
            - "ipa-server-install"
            - "no-exit"
            - "-U"
            - "--no-ntp"
            - "--no-dns"
            - "-r"
            - "$(IPA_SERVER_REALM)"
            - "-n"
            - "$(IPA_SERVER_DOMAIN)"
            - "-p"
            - "$(IPA_DM_PASSWORD)"
            - "-a"
            - "$(IPA_ADMIN_PASSWORD)"
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: ldap
              containerPort: 389
            - name: ldaps
              containerPort: 636
            - name: kerberos-tcp
              containerPort: 88
              protocol: TCP
            - name: kerberos-udp
              containerPort: 88
              protocol: UDP
            - name: kpasswd-tcp
              containerPort: 464
              protocol: TCP
            - name: kpasswd-udp
              containerPort: 464
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /data
            # systemd expects these to be writable tmpfs-like dirs
            - name: run
              mountPath: /run
            - name: run-lock
              mountPath: /run/lock
            - name: tmp
              mountPath: /tmp
            # cgroups for systemd inside container
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 40
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: freeipa-data