apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: headlamp
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:5JtwmGYElUbY/1aHEtsTFvmheC0V2zScHDG3jJ4sF+mnMUkEoR+bOw==,iv:n0mot7f4libnN0CVc8iucLXo6r4Ks86zWKw5m+fgG+0=,tag:whkyXCKHnQQ2PujfrBFiBQ==,type:str]
    client-secret: ENC[AES256_GCM,data:bIGFC8LAg8Jyk4fG/64Ge0uQc8TM1gEqR1v6oUFBxbIMsFiH212Gxj61z+a4JchhTFhwtkietJaCEyqZJ2+lQj8jua+tsWe5/zkOVY1exw/CSTHO6L6EJD4FddOb9wUZ6caatasqS+i9QbMrH71IccYnK1LkkWWej4cJwvbfE4k=,iv:LKLBmfKPBgBVakF+uNcfYy0i6I+UyOtk/dJ2DBkGjfE=,tag:z4D4+kd5gCCn8zOFsFPXHg==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb3Z0RGFOL0E1ZlFKZHBU
            bkRjTnUrRHNoSmdTbFB4TVpPdHl5Z2ZKY1VRCi80M3dObFduUUhkWkVVMUlKaGxD
            M1hYS0dPNW52Y0c4UzdXZnZnak4zZGMKLS0tIEdWNmtGRzZXUTBiU3lxSm5EaEdJ
            bSs0M2wzdEhHMzRMNnJ2ODhTaitBZTAK1gSA3PrGxioFqIpTkwYt6+6U4CKgahHq
            iad/yR9brYl4VZMTBm0ywOWnmLi1kvtXXikUd2Ize4umuN36Yyc3Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T16:17:53Z"
    mac: ENC[AES256_GCM,data:5Fr91Fr+W9DzHH4AFHbEjB8PR+cRx+fb2qdr2QVdDBtXBiGKbCqWo5RKUD3C7P4jke4YmAbLKgCRlL5wdgupYqV2+1H/5yblx+/eFCLTGJvOI7t4ZjoaXJHtKX+SgjrYTxyWVmRbv9Eibhucti9C/oTUh5tY6jHRBrdfwqclrjE=,iv:DdzUaJpgakmCd7dNUM7p+Yf5E2vzEPpZXkBkd+VCbr4=,tag:W2r54sRDzWS64yQC6GHrfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
