apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-ui-tls
  namespace: longhorn-system
spec:
  secretName: longhorn-ui-tls
  dnsNames:
    - longhorn.local.nasbenito.com
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer