apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 1h
  values:
    persistence:
      defaultClass: true
      defaultFsType: ext4
    defaultSettings:
      defaultDataPath: /var/mnt/longhorn
      defaultReplicaCount: 2
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 5