apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lh-test
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: Pod
metadata:
  name: lh-test-pod
  namespace: default
spec:
  containers:
    - name: test
      image: debian:bookworm-slim
      command: ["bash","-lc","while true; do echo \"ok $(date -u)\" >> /data/test.txt; sleep 60; done"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: lh-test