apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin4
  namespace: pgadmin
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: pgadmin
  values:
    existingSecret: pgadmin-admin

    env:
      email: hector_admin@nasbenito.com

    replicaCount: 1

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 5050
      seccompProfile:
        type: RuntimeDefault

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

    serverDefinitions:
      enabled: true
      resourceType: ConfigMap
      servers:
        "1":
          Name: "postgres-main (rw)"
          Group: "Servers"
          Host: "pg-main-rw.postgres.svc.cluster.local"
          Port: 5432
          Username: "postgres"
          SSLMode: "prefer"
          MaintenanceDB: "postgres"
    
    persistentVolume:
      enabled: true
      storageClass: longhorn
      size: 5Gi

    service:
      type: ClusterIP
      port: 80

    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 1Gi
