apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-main
  namespace: postgres
spec:
  managed:
    roles:
      - name: pgadmin-admin
        ensure: present
        login: true
        superuser: false
        createdb: true
        createrole: true
        inherit: true
        passwordSecret:
          name: pgadmin-db-admin-credentials