apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-servers
    namespace: pgadmin
type: Opaque
stringData:
    servers.json: ENC[AES256_GCM,data:wMBihe6Tgk6pCxzepfAuSnzEIyv0btcTxOrOAohWzMGEDlo1rdyeuSKlrYBcx/+rYjxaIwNIrPYQByFcKxhYbAMYF0/iivKnTOhaHgbfndzg0Udjz+FTwCzfY/fTWJQsB6PrfRwasvUJL6TsRZCvRzjt6nuVnkBY+NApLunjo1weyzqkDWAPstwXXw4OdFccELfj/5KR+14FPPwWlQtbAygfU1oFtOqZqqgBVyGVy47xKggYT2wDrljKTmt9NjvE7MYCPW6XU3C5TcSIEcONghiE9UfyRelyYuhobKzdtowSwnTo3gm/RynXnIFsbbQRqkIN7Usvda/OPEzmScNodlG5JiOu4Mi72ycdgjf7KLUGkIBrxnHzY1S9ww+vid7B0blb/HqM6NZW1UvigXGppJfx7ZdpnhID8Gp4Q7JPaHHPprshb1sHbZEFwRe+v/UVWdXNXohVk4wQSS98rqMzZqjoNOQhaWffgMV+CVRfq8BEZCZ+uAQ44uewXox6t50WzeVumYT6xWkQHTaYYxpV5FxDWPHwY4CbAha5KIJc,iv:xoGqjgx2g3+2cCQLWRgWX4B2xk5hR+vZi3/amnChHdA=,tag:FbaU7jEVJbpRbNyZTfh1BA==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOVJGa0FsaE4vNUxDYWZX
            ZnFuRFgvUXpYZGtWeWM3NTVXa2JqejJzUzIwCmFsSDV3RnIyVGt2NTJhS3V4Tk1u
            WlNGcm05MEd6NUdVdFRnR2pxRmIxM00KLS0tIFJwWWFSRmwxS2xCeDVFTjRSeVVn
            QXF1dzBoQzRieXpudWl3NjkwOEwweDAK+pgt5wQZlQN+yUycfbl/3/W8JTpPWYX0
            IZ7UELBYx0CJLL9qpbg6vSHEqqvzb+Ouhq+dljyj48MK7h7fzlggMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T14:53:46Z"
    mac: ENC[AES256_GCM,data:79SsNo6KtIAdrZerkQECRNnRMHB9uo+Dgul+yynsv/iTkiv8WzKyBURxAiFpcgWj3TCS8n2BD6OQd17qBjzaXI2nuXXSMOGOxb0x3RQMqrRMxMCKZUrtmdCtGXhr2+jUay0VyGKf6S0zgN+5dAOjmqVivlv0qINwv62K9496AsM=,iv:umNZ3WjGX7j+a3Z04FFgxDAHLw6VWF81KIVmSWaO1FQ=,tag:U0nk3W4Vy2yMZCx0MWL43A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
