apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-oidc-secret
    namespace: pgadmin
type: Opaque
stringData:
    PGADMIN_OAUTH2_CLIENT_ID: ENC[AES256_GCM,data:lXxQ8/lZpbMYy3AZUCgq4BciqQIBjHNL04eP4FO8R3Khd2X1j4ylEg==,iv:DcxlbBhFo07+RRKmqZ+wcOnIY0D6HQSU+0/OQVjpeKQ=,tag:7+loMBsqx0/uZ6XjYWTLqg==,type:str]
    PGADMIN_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:1vJD9y51+WobPsXKr/J3LdyyfQrlFGTGwhbJlVe8E2aMjExIn4YO0DKB9H7oYIXnWC4pmU9rzHya1N4YGqMkld6qVZeLjxoiFVPDe3DCihMoumhrCQ7u8eqgmbtux3nBc0pMR1JgaWNNlPUe0PsMLL+7fcLY5QnaMExUFcHZzmQ=,iv:Co1AJlUcPwZnc77IAOoirI7djEy20vLUndjpL7A3kXo=,tag:9WBil6yP/QgTV4sToe/SrA==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNU3ZCUFVjVUF4QmxiZGw4
            MGEvSzRhTFE2ZXp2RHdaQTd1bGpjd2xYUVRZCmNLeGh2UjhiblNtd1VCdmoxRVov
            T2Z5V0FIU2xDaUp2cDR2TkdoVmtSUUkKLS0tIGx2WHdHeTF6RWVvdDRMbzc5emZI
            UmlvSW1HTGxUOUtMRHJPMi9nU01JcFEK4OAV8MF4rEXFfmgPiU02TEFk/CkcCPKw
            K+Ck2XCw/F9YSHiS4v76BtsnGLyLKNsO0agEcVzlOhWd9WY0DpGGXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T15:49:41Z"
    mac: ENC[AES256_GCM,data:s/V/RqxEL21WFy6IoYbIxvBeao9KXIs6/gpa08aBBOTtZzaHoLEp15KGR8NSLVkFI3+ZCoTGGbGR077zChoB8t1+opHVPydbWdGVqiwpq7VQWKHtfiYjRuIbfNXPKysF4Ec+IbJk+/egKgYe1fc9XDS48w7C6geHl5WDS1lm4ZE=,iv:UsbxZ3xUmSzHK+yTD1uKXNVSwAgKnTXTV55ZOubIKL0=,tag:aiQ6f/tLFqBnBU3p8/dxFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
