apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-servers
    namespace: pgadmin
type: Opaque
stringData:
    servers.json: ENC[AES256_GCM,data:SzetVENXQM1OAbtYYoafxdXEcKuhm1rHfaTcpt+ZFlIFdioG0picQZ+WLVCKtwjHn2SanJf8HG8Z025Yj5BExDxwguIzWCDNMfvBuFCbOt4TevkRw3jPZ1fNiCCMNDaG4r4KhU0PHPRcS73S6tNiCDzdk/ATJ50o5ACaCRQlA5UgLXxPz96DP59BPx5fnnqoHptpMYw07vX0Ld9+HOKICP6U5v5pdTQ+wGTdWIOvWoCZU/q6tCGAP/SGTkDuVILvKXtjtQiKs/VRo8UHJAxNUi+nxxLe3vlxE33AOyCchGvz1ebz/L9GV6rFauuya974eAsSiPRYQ1soWihSe3p/s3IKkmG5rmdAVNU4UqsfxrUAnEXINjag8M08umGcn9mheKR9Q/5w/t/7XoniKnaNx5pOnPckFVt6v7bEl0x9HMbRBoZx9yoO/rMQLK2aT+gQkJbHFRSQ9F0JYV9Fv8ICEsdZUv2rcRN5dml+DqTkc1UTkAw=,iv:/iaTEIQr4bK5NttLwKLBNZiMrlU6FONYzx8Bxm/gjWQ=,tag:+0RLP6cMJdcaFJIxo517yA==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOVJGa0FsaE4vNUxDYWZX
            ZnFuRFgvUXpYZGtWeWM3NTVXa2JqejJzUzIwCmFsSDV3RnIyVGt2NTJhS3V4Tk1u
            WlNGcm05MEd6NUdVdFRnR2pxRmIxM00KLS0tIFJwWWFSRmwxS2xCeDVFTjRSeVVn
            QXF1dzBoQzRieXpudWl3NjkwOEwweDAK+pgt5wQZlQN+yUycfbl/3/W8JTpPWYX0
            IZ7UELBYx0CJLL9qpbg6vSHEqqvzb+Ouhq+dljyj48MK7h7fzlggMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T18:17:56Z"
    mac: ENC[AES256_GCM,data:Wa4ctmcW3S+Q93/X8P2EX+GJdkin0BTZt9opjHLu1PwZ6G5JSnRUwkUcXn51VehC6k6LXtraWYW7s9ZqFGVDNCi7wnl0atxJeCVnwQlxuenT6KNw4Ye24FepoaX+7ddiLOI4FcrbyGLHFwHeWp3pvMrGkzGBjLCSjw2q7BP90B4=,iv:wKAtuD+WED4L7HyDdIjH+u/S9ECsnh2WIcqSytn49zc=,tag:XW3LEOF8maY439a64ImgDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
