apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-admin
    namespace: pgadmin
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:NrD2OoqirjyEru0OqkP4I2wufyGbu8mGuns=,iv:i722F0akXcnDJpw8EXUScJVPPkZrSLhQLxsoogq/Z7c=,tag:xtCTaYb0yMOzOF2+C8wV2g==,type:str]
    password: ENC[AES256_GCM,data:VtwT6kTczMgDTJmxg8BF,iv:6IHHfjuTkYkL6wvhf3+quyPLOVbhvTK4MitpRZFEWuQ=,tag:JWXsG1fNfIA9oOXrqWcoTQ==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydmhKa045RDAzbi9ZRnFl
            b2FDRktBcWlLdVlldGhqTzdaamFoNDhxbjJvClp6SVBJSDVCZHJqb1pFKzhwSlJQ
            Z2ZKdlY5ZGZKYUdtT3BOcGRjRitSQ2sKLS0tIFV2bDY5ZVk1RnRiSkVYUU9HRVZT
            S29ZZW5DQkNMaXVPeHBwTHFMbWk2NFEKNqjivO65CBmAluT1s3WQ7EjczF2XdsFw
            Kx1c8D+ffKFmcOJO+Hhg+toiUkR8+FZA6MBKVQN04EZDrK0M92eb3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T21:02:07Z"
    mac: ENC[AES256_GCM,data:51K5o5HBgOzgyTbGBJLUM9xW+4xLCzqqSvG7UQMHOsVk8vwbrjr01BxLPNky2kAcvFJDD2qUbLw2kRPeHR9y5YngzM2M9+3HYpCATM/nGosZd3oqF3NXdTeRewGUb4XDjrMoMyEwZQadJ7DpB/25wZnn2dciw7SsV9ZK25rLokU=,iv:S3asHRp4qysBSGEALC8ZNVBq87+wvGwyFxpmvPzb/EI=,tag:oL/Ql5RX65cEzKFdCHj9Ug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
