apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-servers
    namespace: pgadmin
type: Opaque
stringData:
    servers.json: ENC[AES256_GCM,data:VlmmPUSS83UUQmNdFTW6Vg7a7E3SEmopFup1WjUyZ+vlqZop6ygVmI7IlIvchtyUgzRgvbxNGovUN9VALNOhv/D91KIZYfs9E9HzUyDXZRW1q5ghr8N9M6gRqHwDzj5h9qoRT1IpJ4XMC7MhwIC4aLdOL/RLfR1hTQKeQK17JWziv9rCLCieNBN6hhY9W2yPAMpZY1HfgGrkMHXE6U6V/7kZPVsbObOJIOLrxC0a5qZ5RENb5HWSC5+I+RTeqtc4WXsF12YCkFMmWSI4IsFVFJWPQ1RuLuc09t74vY4AqMLhxkPbg332ZOb9sGQscMDxszpmeEg9S+IojQB481dGogj1ueAnhL1VlUDZ0xc=,iv:amWln+iNqgy6yhrs/cAro5kB45MzzWnXC9VdLlkZPEk=,tag:zs2bdW/3Mw/X61g+uQ9LgA==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOVJGa0FsaE4vNUxDYWZX
            ZnFuRFgvUXpYZGtWeWM3NTVXa2JqejJzUzIwCmFsSDV3RnIyVGt2NTJhS3V4Tk1u
            WlNGcm05MEd6NUdVdFRnR2pxRmIxM00KLS0tIFJwWWFSRmwxS2xCeDVFTjRSeVVn
            QXF1dzBoQzRieXpudWl3NjkwOEwweDAK+pgt5wQZlQN+yUycfbl/3/W8JTpPWYX0
            IZ7UELBYx0CJLL9qpbg6vSHEqqvzb+Ouhq+dljyj48MK7h7fzlggMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T12:13:45Z"
    mac: ENC[AES256_GCM,data:BOAcg6F+tZAH310fy4xbpJpHuu93s+xpAkSWs9dBGUHlVNlpC5gmUgJrWS7hA91JwjbekcU2ahL9nMTrNu9irdtiNR2b9ieHKHjtx+ytAZqR1Po4vst+aBVBVyuUcntM8mdc0mE9msB9lfNRIyMcQRvNYk9P1EcNXic3U4F4yts=,iv:5CGcSMtHnRhamNESObnAIe5M4rolX/DObvqnCamoIp4=,tag:6rvpJM9s/0SMbrQ34vbSDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
