apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-admin
    namespace: pgadmin
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:MPzZPauaimKYDcoKVLo2uFI=,iv:Rc+VxOKBFYGWoB24+VqsbB9cyKO2+gajnTLWT5XsdRU=,tag:58oEhemqCy+Rrf+qji1jNg==,type:str]
    password: ENC[AES256_GCM,data:vcPKfxs4E4/ZrNElpY696OKSIAxBd3r0xeKTGzru0zk=,iv:VaTLXS3LVAGTjj5+KchH8hwozp0L4wG7QcjisLFMLA0=,tag:4TZuiSIe7i3F6r4ZHUmJHw==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydmhKa045RDAzbi9ZRnFl
            b2FDRktBcWlLdVlldGhqTzdaamFoNDhxbjJvClp6SVBJSDVCZHJqb1pFKzhwSlJQ
            Z2ZKdlY5ZGZKYUdtT3BOcGRjRitSQ2sKLS0tIFV2bDY5ZVk1RnRiSkVYUU9HRVZT
            S29ZZW5DQkNMaXVPeHBwTHFMbWk2NFEKNqjivO65CBmAluT1s3WQ7EjczF2XdsFw
            Kx1c8D+ffKFmcOJO+Hhg+toiUkR8+FZA6MBKVQN04EZDrK0M92eb3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T17:55:57Z"
    mac: ENC[AES256_GCM,data:Z3reS0doY+dohuOCZ30V3ah1oJHCD9NGEQA3yFhog3vv/beMmD7iXB6jJwJYgn8iAQNrDJlYHbOBE1ufWezDoQUHM6aHQaS4Aql0sy5YRZmuCHxw9SDZ2oQDwdmH4NGb++c81XI0k+FBIqnYEULtFUF8g7XQJMFiWG3IHZt7bpg=,iv:ahCY2cA8/hg8ROUmLmCMK8WZffbccAKPxs+WI53+PWY=,tag:YFHTCDyyXBhvbAU1ZMqu7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
