apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: homarr
      version: "8.9.0"
      sourceRef:
        kind: HelmRepository
        name: homarr-labs
        namespace: homarr
      interval: 1h

  values:
    # --- Storage (DB) ---
    persistence:
      homarrDatabase:
        enabled: true
        storageClassName: longhorn
        size: 5Gi

    # --- Ingress del chart OFF (usamos IngressRoute propio) ---
    ingress:
      enabled: false

    # --- Env: URL pública + OIDC ---
    env:
      TZ: "Europe/Madrid"

      BASE_URL: "https://nasbenito.com"
      NEXTAUTH_URL: "https://nasbenito.com"

      # OIDC only (recomendado para evitar confusiones)
      AUTH_PROVIDERS: "oidc"

      # Authentik OIDC
      AUTH_OIDC_CLIENT_NAME: "authentik"
      AUTH_OIDC_ISSUER: "https://auth.nasbenito.com/application/o/homarr/"  # OIDC_SLUG=homarr (trailing slash importante para Authentik)
      AUTH_OIDC_URI: "https://auth.nasbenito.com/application/o/authorize"
      AUTH_OIDC_SCOPE_OVERWRITE: "openid email profile"
      AUTH_OIDC_GROUPS_ATTRIBUTE: "groups"

      # opcional: mejora UX
      AUTH_OIDC_AUTO_LOGIN: "true"
      AUTH_LOGOUT_REDIRECT_URL: "https://auth.nasbenito.com/application/o/homarr/end-session/"
