apiVersion: v1
kind: Secret
metadata:
    name: auth-oidc-secret
    namespace: homarr
type: Opaque
stringData:
    oidc-client-id: ENC[AES256_GCM,data:h4TsI6/wA5MEkQLKwr/JLPtX7ddKwtD/jhdzA5bEtyC/SM/qDYX2wg==,iv:kUdf/M1ZFFlRJBvsFCZy54B3Qt448b6parp0lgHFoUc=,tag:e294ldyiWX2k1C4ahCxg+A==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:RaEWr3RymJnhPFat6tEebB+hTLwqiJnbOHWSKUFWmZ7pqcpRijPoOhKnslfIsTKbZBOrtkNcY6SrDZZNFQV1lo2Qni0/rE4RQEXgrHRtU4XRfK1gUXvM9IUAUE8Rykttp0QaivanNlbh5Gda/sot6ori5mftwH1JfK4ZvIzuzfU=,iv:VKge6vE2cgzZcsgLzEdTAAbooSyLLfLaZmGlOc94Nh4=,tag:IkaaAO90QusC/fgHLRSHFw==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TDFObjM3NkdDRTZLYmNw
            d0NFU2QrTlNVSVF5WURZTVlSSlo1WWJKZDFvCjBBVG5pVW1LQXFld3JiUUhmaktn
            dHdUdk0veDc1V0lrSk9HblpialMxdXcKLS0tIHh4QUFxVzM1dmJDMU5mVGJsc1hq
            ZS9RN1EzelBLY2M1cFc1R1lCUTR2d0EKC2v0ow8SzsrIME1dRZfbWgAReFzHGj1i
            naN01D0ZyaW6lJ7yAj6b5iGlrXOb92w9qVR6PegRl4kyJUzzK/JsEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T16:09:17Z"
    mac: ENC[AES256_GCM,data:EWRM9SrcflMveJM7WXjkwyE3sZgQwFfwu2mrP2eHqHsGQw5Z7aaok1weieHEO0c0u642ydgKCadUdarFKftnshjoLY6zvHfYoX7S0ycXYcArVvMolv19c9G38zhO60TNswCqtkYQ0R/RQ7jeq79fLCN/ME4T2S1qeegqc9oxf6s=,iv:qukyuQm9yVY9jB9XRqemzg8WwZNr3zrpv9iwFiS9TlE=,tag:igk6DEtSc5ZXxPFMGx7tRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: db-encryption
    namespace: homarr
type: Opaque
stringData:
    db-encryption-key: ENC[AES256_GCM,data:EvuuM1BOQFriLS+8a/9KZYPH5X6/6NR0UFbOQ/K3fPoyzZlj9e2S7qYQZ/Z5mTqaWpQIl5K+N9I5ZGQkcCuN3g==,iv:tpkrvhSijTilv9080qlKzoE6qVDQC25hkmB+iv4bU9U=,tag:C+HtyDy/LI9m2EbNYTkFnw==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TDFObjM3NkdDRTZLYmNw
            d0NFU2QrTlNVSVF5WURZTVlSSlo1WWJKZDFvCjBBVG5pVW1LQXFld3JiUUhmaktn
            dHdUdk0veDc1V0lrSk9HblpialMxdXcKLS0tIHh4QUFxVzM1dmJDMU5mVGJsc1hq
            ZS9RN1EzelBLY2M1cFc1R1lCUTR2d0EKC2v0ow8SzsrIME1dRZfbWgAReFzHGj1i
            naN01D0ZyaW6lJ7yAj6b5iGlrXOb92w9qVR6PegRl4kyJUzzK/JsEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T16:09:17Z"
    mac: ENC[AES256_GCM,data:EWRM9SrcflMveJM7WXjkwyE3sZgQwFfwu2mrP2eHqHsGQw5Z7aaok1weieHEO0c0u642ydgKCadUdarFKftnshjoLY6zvHfYoX7S0ycXYcArVvMolv19c9G38zhO60TNswCqtkYQ0R/RQ7jeq79fLCN/ME4T2S1qeegqc9oxf6s=,iv:qukyuQm9yVY9jB9XRqemzg8WwZNr3zrpv9iwFiS9TlE=,tag:igk6DEtSc5ZXxPFMGx7tRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
