apiVersion: v1
kind: Secret
metadata:
    name: auth-oidc-secret
    namespace: homarr
type: Opaque
stringData:
    oidc-client-id: ENC[AES256_GCM,data:K9ZXhvJL25sd/28NggNrqQ0uUoRcrVeT4vBlz96fH+DUPwx0p9qwew==,iv:+xKi4OXbQREvcmoiJF9cO+1u7vcbIdwD3uYFBCXN0yw=,tag:cvM7Wrt4ob4YmBhQnTjvZg==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:vhdSLuChbdNBaPjWLMVerxgiDGuW+ekIfidzV/Iq6usA+5KL6vlAJsE68+g5EjoVayIlzmTth/siw4EqkxCct29491v7sNcOdENDAtFs2+1CUW78KqQPu67hAShf31UgpbBerPLgE0LYRdcDCnb43zm9QQA1QRQ/rIdwThBUEyo=,iv:Gsaa7h73uPCcaRUvvQfTxf2SGQ1FWFoUFtsz/SaXhc4=,tag:8uYIEOmMjb10zF41RltLBA==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TDFObjM3NkdDRTZLYmNw
            d0NFU2QrTlNVSVF5WURZTVlSSlo1WWJKZDFvCjBBVG5pVW1LQXFld3JiUUhmaktn
            dHdUdk0veDc1V0lrSk9HblpialMxdXcKLS0tIHh4QUFxVzM1dmJDMU5mVGJsc1hq
            ZS9RN1EzelBLY2M1cFc1R1lCUTR2d0EKC2v0ow8SzsrIME1dRZfbWgAReFzHGj1i
            naN01D0ZyaW6lJ7yAj6b5iGlrXOb92w9qVR6PegRl4kyJUzzK/JsEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T16:25:13Z"
    mac: ENC[AES256_GCM,data:PscN5DV9B3xBHfO0z/LGAxRBTszLJS0Mx20msjlHAEHaO+XxX05b8HXgmEbAProtMx/JvvHbiwzJWb8twXtdvEp5/JGrpThZ0Yc+1aWMx9OG2smMIr7d0In1JA3Oie1SBT5R4jN3skWxqvcyfUj/6dc0D+AziJaj8/bnUoGDRPw=,iv:LOHwCEYIHUo7tX8RYSmR83YqRl/N7W7X1D7zHfNyblM=,tag:2+A74ApIeXTFMWBxPi5h0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: db-encryption
    namespace: homarr
type: Opaque
stringData:
    db-encryption-key: ENC[AES256_GCM,data:EvuuM1BOQFriLS+8a/9KZYPH5X6/6NR0UFbOQ/K3fPoyzZlj9e2S7qYQZ/Z5mTqaWpQIl5K+N9I5ZGQkcCuN3g==,iv:tpkrvhSijTilv9080qlKzoE6qVDQC25hkmB+iv4bU9U=,tag:C+HtyDy/LI9m2EbNYTkFnw==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TDFObjM3NkdDRTZLYmNw
            d0NFU2QrTlNVSVF5WURZTVlSSlo1WWJKZDFvCjBBVG5pVW1LQXFld3JiUUhmaktn
            dHdUdk0veDc1V0lrSk9HblpialMxdXcKLS0tIHh4QUFxVzM1dmJDMU5mVGJsc1hq
            ZS9RN1EzelBLY2M1cFc1R1lCUTR2d0EKC2v0ow8SzsrIME1dRZfbWgAReFzHGj1i
            naN01D0ZyaW6lJ7yAj6b5iGlrXOb92w9qVR6PegRl4kyJUzzK/JsEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T16:25:13Z"
    mac: ENC[AES256_GCM,data:PscN5DV9B3xBHfO0z/LGAxRBTszLJS0Mx20msjlHAEHaO+XxX05b8HXgmEbAProtMx/JvvHbiwzJWb8twXtdvEp5/JGrpThZ0Yc+1aWMx9OG2smMIr7d0In1JA3Oie1SBT5R4jN3skWxqvcyfUj/6dc0D+AziJaj8/bnUoGDRPw=,iv:LOHwCEYIHUo7tX8RYSmR83YqRl/N7W7X1D7zHfNyblM=,tag:2+A74ApIeXTFMWBxPi5h0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: homarr
type: Opaque
stringData:
    db-url: ENC[AES256_GCM,data:6XXM8pr7KZ8AkywB3mGt1BuT3krlgWJuyq3Dcs1ibW9BvC1lMWBrcOJriXYCcvTGGxLlaYCd+dvqYn4PLEH7AdnIAXZrdEWlt6RkZrz50TCUEPNwSV5Ybzc9g7SUIXq2N+hCgJCK5YanVXLoM/bdvXf8nVGTcw==,iv:a8w78aAd0C/vp2mKNTdyMd/BqIJ5pRuDVpjbXaeaNOI=,tag:CAKIq6PTzyFzoGwOGkKz6Q==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TDFObjM3NkdDRTZLYmNw
            d0NFU2QrTlNVSVF5WURZTVlSSlo1WWJKZDFvCjBBVG5pVW1LQXFld3JiUUhmaktn
            dHdUdk0veDc1V0lrSk9HblpialMxdXcKLS0tIHh4QUFxVzM1dmJDMU5mVGJsc1hq
            ZS9RN1EzelBLY2M1cFc1R1lCUTR2d0EKC2v0ow8SzsrIME1dRZfbWgAReFzHGj1i
            naN01D0ZyaW6lJ7yAj6b5iGlrXOb92w9qVR6PegRl4kyJUzzK/JsEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T16:25:13Z"
    mac: ENC[AES256_GCM,data:PscN5DV9B3xBHfO0z/LGAxRBTszLJS0Mx20msjlHAEHaO+XxX05b8HXgmEbAProtMx/JvvHbiwzJWb8twXtdvEp5/JGrpThZ0Yc+1aWMx9OG2smMIr7d0In1JA3Oie1SBT5R4jN3skWxqvcyfUj/6dc0D+AziJaj8/bnUoGDRPw=,iv:LOHwCEYIHUo7tX8RYSmR83YqRl/N7W7X1D7zHfNyblM=,tag:2+A74ApIeXTFMWBxPi5h0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
