apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-credentials
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:n7FvWBNY39A5,iv:LN+J6rsOJf3mfOn8bRxSanR9yFhvAvlLUymDq5aS6/8=,tag:fyaVEiDjwTLem4wbEAAsBQ==,type:str]
    password: ENC[AES256_GCM,data:/bqwXKCJ2oAO9UyeQ6cyY3VylFmBJJj2dTMA209bLCH5U7+eicOOW71/FSi0HdSmzW+QDGvd6M1oMVLkhy1Puw==,iv:qZ97gQSg7slxp0SatZY+FDllPWpKFbE9YvtE0ZDwhj4=,tag:U6CyNyWFujnJZ7KNRYR7mw==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObWdpSVVPTklYTmxTYUJJ
            WVY1T3J2NktYWHR2ZlBvNEJHeDBacDB2akgwCmZZOHdTWWdZTGxONnFCZjVFWmFC
            RnpCRTRpdU92OEgxbEVZdklvVk1KNDgKLS0tIFg5TWMvOGs5dUV1eFB5RnJ4ZHhk
            SlUybGJyR3IvSkt0aitwSXpLam0vVDgKJqlSbIhqQT6j3E3oKZLkK70LcnxYh8Hh
            jqKv3Zy/urLnUU3g4QiKfUCgY2hWXZaatKSuaZYD54ruS8f2J9ug2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T11:05:00Z"
    mac: ENC[AES256_GCM,data:8L6FiGZDQDrAj5XSW4Aev7dbTSx4CXW55RpT/r/Ciku0gjbhNrpvdVni9ve6bV9RSjT8sahcY3ziVhhqC7UpvBnXd/5xfsEGV3FPwOfpXZx3VPmQS6M7a+CxUjo6fcpBqMKt4k2jpht3XsYr871RFQnmpPZQCxsNmH+QGGFP8fA=,iv:NhEQmmkqa7dsxW+aWtLN0cszdSRSF3FA1rFwRWduqSA=,tag:wechneRdTa88NgtBCa7IJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
