apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3
    namespace: postgres
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:N2D3Tn0E9hWc9A8=,iv:e2q/wuyl3H2whjzKCLWnztI0eVV/WzSTPzZtCB8/jhg=,tag:tb0XC0pEJ4l4I2U53runoQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rP7gP33OBf4dGafq4k2MX/z2r9bAb7MaCCjyaXEAchAuAydlQFgU9EbkdgFLeAE5eic=,iv:W6P0ApwXnNQgu6A9+/sTCTSdgel30INCnbXT9nMolS8=,tag:vJ7eHrc+c3xqOdkZ4Aq4hw==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMml0RjhPN256RkdFaVNR
            cDRhUXk2dUhNb0QvU0hZQXlOUVV3b1FETlQ4CmJHQ3FFdzdXQ0tTdWVHU1BDMllV
            QnpidCtleENZaUFqcHRMTC9KV29yN3cKLS0tIDRpOUhyTjA0THZTc3AzNkgwTjg2
            eTJhbUJpQU5yTWx4cHRGRmtTb0RzUW8KYCYxi4slda3YiuCbEuN5SQB19T77Lik7
            lwMBpw9m+suk5RcmfrxqWb/FGknal0yqI7S5fGzrio8B0BdB8RPTcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T21:01:33Z"
    mac: ENC[AES256_GCM,data:u+lHmtZY+R8GBrGK0Fn1w9MI+ThndOyD0ikEV9gvXsvPWPKkmKphKqPvzhYrVKLgWBT52ANuj5gp4PBjiWEkPOVT2eK8JEjkdkNFBPemFgK3Qs1JBaMKyEveqvDgnDJsDivz+C5/m6M+LR6E3fP4U2UKNJua484hqpbRANn+ysI=,iv:5ummIC/vtK78CXpjC6jAExB2X0xtlDCkA0H/23FaTsU=,tag:gK+lGixh+phDECIasxxFLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
