apiVersion: v1
kind: Secret
metadata:
    name: pg-main-backup-s3-creds
    namespace: postgres
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:N2D3Tn0E9hWc9A8=,iv:e2q/wuyl3H2whjzKCLWnztI0eVV/WzSTPzZtCB8/jhg=,tag:tb0XC0pEJ4l4I2U53runoQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rP7gP33OBf4dGafq4k2MX/z2r9bAb7MaCCjyaXEAchAuAydlQFgU9EbkdgFLeAE5eic=,iv:W6P0ApwXnNQgu6A9+/sTCTSdgel30INCnbXT9nMolS8=,tag:vJ7eHrc+c3xqOdkZ4Aq4hw==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMml0RjhPN256RkdFaVNR
            cDRhUXk2dUhNb0QvU0hZQXlOUVV3b1FETlQ4CmJHQ3FFdzdXQ0tTdWVHU1BDMllV
            QnpidCtleENZaUFqcHRMTC9KV29yN3cKLS0tIDRpOUhyTjA0THZTc3AzNkgwTjg2
            eTJhbUJpQU5yTWx4cHRGRmtTb0RzUW8KYCYxi4slda3YiuCbEuN5SQB19T77Lik7
            lwMBpw9m+suk5RcmfrxqWb/FGknal0yqI7S5fGzrio8B0BdB8RPTcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T11:09:04Z"
    mac: ENC[AES256_GCM,data:UAsoyV46IAkwlBYWvJb6tfMMYasnee02r7EYgUgzZFCRGtYkDNB11gAuo+EcfzfW22n3Z6HdO8A9fxj4XhdkiC7kC28FTfdkFRXwaFqDTzXrHIP1eSaE2S/NlW16OIX/p54g7almV5tJLVmwWFJSUD0MQtue3H582fh0vYFFu5o=,iv:LPlNeQupLpH9j2MN4G6hKMLqp03VQiKYkSZQbz078B8=,tag:9UOy3FjYoY75gGfxjQFwMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
