apiVersion: v1
kind: Secret
metadata:
    name: pg-main-backup-s3-creds
    namespace: postgres
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:X/u9Pz2Hutz0VAk=,iv:SPO1QXjIpCB7xozM/QGL2vkFa8vgaIawBjgrrO2wpIU=,tag:pvwpbL+YVSj8YH6ELev20A==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:To8rejuZTpeJR+v+HfZVs3m9yWZGPj5dryHJQvbaqJ4wQ9lUKAxuO30j/ZHwxG+5IY8=,iv:gIi7aD8dB0hQaKcWhDsiA0mRS7JXm+OszEmhu/gfe7g=,tag:vPUWnqJ44yQLtyAA1oo/sg==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMml0RjhPN256RkdFaVNR
            cDRhUXk2dUhNb0QvU0hZQXlOUVV3b1FETlQ4CmJHQ3FFdzdXQ0tTdWVHU1BDMllV
            QnpidCtleENZaUFqcHRMTC9KV29yN3cKLS0tIDRpOUhyTjA0THZTc3AzNkgwTjg2
            eTJhbUJpQU5yTWx4cHRGRmtTb0RzUW8KYCYxi4slda3YiuCbEuN5SQB19T77Lik7
            lwMBpw9m+suk5RcmfrxqWb/FGknal0yqI7S5fGzrio8B0BdB8RPTcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T11:25:15Z"
    mac: ENC[AES256_GCM,data:g7fdz79sqeDMEGBHBVqif5xL+1b3t2g1+EBKUZZMv7dagF4gr+wXzmDSYDp09otKiXcpffd/LZXnDIrKteivehkLJXZogSmZg84lDCRGRZXrIQiD9GMv5D0YMTwBqKZ3O8V4zPAawApYeK42HqviVoblQjzJdG3UIMFpTzNIc/c=,iv:q8T3YRKWnjhpINa60UEdg/n6H9hWcteUQ27wUOeyUVU=,tag:3kWly7asXYBKDp6ULYMZPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
