apiVersion: v1
kind: Secret
metadata:
    name: homarr-db-credentials
    namespace: postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:gLr6CZTr,iv:B6GikadjKofXivvJ1Vh5HcNRaBPdKoHvlIjllPh7tNg=,tag:0KaJW2oIx/0z377k5xDbJQ==,type:str]
    password: ENC[AES256_GCM,data:arD0t+UKKu9gAe1idk9JNNh5KLEGt781wcmAEGgxBX87hch6GmTXoDmgqem7cTff,iv:tOI1jmqFBnJOz1lwljz3pMZHenWowLrUPbMp206oDDE=,tag:R1pZlye1pv+ImXrgIKTN8Q==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaDNWY1dKSlZrUkNWdk9W
            aHVvTWhKbThiMjlLQnMvd0t3bE0rMnRZSGtFCkRvMWRYd0QwNXBuSjI2amxMYldS
            aXJoUDFZL2d5bDRMUDlCRmx2ZytEbEUKLS0tIGtNQ2lvUDFMZWVLeUk3UW9FTXVm
            ckFOZk5tOXdxWkRQazhRRGFlVk1kRFEKysQTNdVdj1Hw9PPnocjLIbWxymL6qJzc
            uIAN4dE5F+ZweeMaLHzjIM8EAgSxCNbQSbX4F6FHrZ4dQ7rXWmHMHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T16:10:18Z"
    mac: ENC[AES256_GCM,data:UNlwY9vpxB+xEkHU+ALNpIcmRKbkmFu46S3ZGV1Tui6fpJHcNJ7f9IulPYJDbfcfH+ET6YsRtFw+cu/aYEHvDlzFdDxi/1jDQ+3Y0zU8UNnMs3o9oK/ptMAurzq0npdkkNV4AYGjaLSYjHvPBtwHZmGKne0x1YAJLOuA25Jke9A=,iv:Uwd0c/FBd3tHTcj+yUEounl2iGFFfb/DRBBlTtZi+ZE=,tag:AVUGMz4jqMReoYmUF10L7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
