apiVersion: v1
kind: Secret
metadata:
    name: jetkvm-db-credentials
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0RpTLAQ9,iv:SrwjSw8YipGBq3dyiCS9Xb/KwqyZzfqYkr3SXah6KPM=,tag:sKZxoGetX2OlzcQie0zhrw==,type:str]
    password: ENC[AES256_GCM,data:GnDBQ1SzdGLDTibN23Oj/3rx9+/kBOJ+kFVVafWKzQPAXGv9QKD6GycfTI693vLi,iv:cwUOCiFEbFYSW4u6Q6C9xLCnVum8k1VLpzUu4t2u8/Y=,tag:7bFI7zEgAXeO0s0WOFtPiQ==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByS2JZM3VqRWNsdWkwd2xt
            cytrVzdadW92MjJjZ2tIQklCejlBanFCWXl3CjVPQWdsNUw4ZjJNYldvQjgxd0dw
            NkM4TTg5Y240NjJza21TdFBoeUt4STgKLS0tIHZ3V0pDQnEzSWNka2xTL003Mk5Y
            Wm1keW5OQmJqOVI5STRuMHM0bzVLUU0KtXEbFFZE/gspBPk2vagWRPjX3HAltksK
            35cOEccVdL4SzMua74lVBStcyukD3lcOpn3knK52A1hovOAQsSqPjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T18:41:22Z"
    mac: ENC[AES256_GCM,data:ONMWL2Eg1lWWnBx6MklFmA5k/R4zugXRmBZ5iSW7TeNPoRQNJrNgDonh0/cNXvJSMSNuPor/9jbrmKALAnvMy/hPFhojuEs8E7hrKQOZGLau5EyM2NY7ISx924ZqvvVwVyJiZBEJCi1ljtx2eojOXCIqoFw9ILvmLVltnPxZBCw=,iv:QmikCWNEM5749xySLRIWbdY9SDn8AtGKgfEoLyB4VpM=,tag:4Nki/FCw6aTPtt1f5jDmGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
