apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg-s3.secret.sops.yaml
  - cnpg-cluster.yaml
  - cnpg-main-minio.objectstore.yaml
  - cnpg-scheduledbackup.yaml
  - pgadmin-db-credentials.secret.sops.yaml
  - authentik-db-credentials.secret.sops.yaml
  - authentik-db.yaml
  - homarr-db.yaml
  - homarr-db-credentials.secret.sops.yaml
  - jetkvm-db.yaml
  - jetkvm-db-credentials.secret.sops.yaml

patches:
  - path: postgres-managed-roles-patch.yaml
    target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: pg-main
      namespace: postgres