apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-main
  namespace: postgres
spec:
  managed:
    roles:
      - name: pgadmin-admin
        ensure: present
        login: true
        superuser: true
        createdb: true
        createrole: true
        inherit: true
        passwordSecret:
          name: pgadmin-db-credentials

      - name: authentik
        ensure: present
        login: true
        superuser: false
        createdb: true
        createrole: false
        inherit: true
        passwordSecret:
          name: authentik-db-credentials

      - name: homarr
        ensure: present
        login: true
        superuser: false
        createdb: true
        createrole: false
        inherit: true
        passwordSecret:
          name: homarr-db-credentials
